import { ThemeVariables } from "../../@types/theme";

export default function ({}: ThemeVariables) {
  return {
    logo: require("./assets/images/logo.png"),
    arrow: require("./assets/images/arrow.png"),
    bank: require("./assets/images/bank.png"),
    money: require("./assets/images/Money.png"),
    trash: require("./assets/images/trash.png"),

    logo_white: require("./assets/images/logo-white.png"),
    card: require("./assets/images/card.png"),
    wallet: require("./assets/images/wallet.png"),
    icon: require("./assets/images/icon.png"),
    line: require("./assets/images/line.png"),
    chip: require("./assets/images/card-chip.png"),
    icons: {
      signuout: require("./assets/images/signOut.png"),
      device: require("./assets/images/deviceMobile.png"),
      star: require("./assets/images/star.png"),
      user: require("./assets/images/user.png"),
      users: require("./assets/images/users.png"),
      customerSupport: require("./assets/images/customerSupport.png"),
      identificationBadge: require("./assets/images/IdentificationBadge.png"),
      wallet_icon: require("./assets/images/wallet-icon.png"),
      withdraw: require("./assets/images/Withdraw.png"),
      send: require("./assets/images/send.png"),
      receive: require("./assets/images/receive.png"),
      list_bill: require("./assets/images/list.png"),
      dark_users: require("./assets/images/dark-users.png"),
      education: require("./assets/images/education.png"),
      dark_user: require("./assets/images/dark-user.png"),
      investment: require("./assets/images/investment.png"),
      electricity: require("./assets/images/electricity.png"),
      passport: require("./assets/images/passport.png"),
      reverse: require("./assets/images/reverse.png"),
      flame: require("./assets/images/flame.png"),
      solar: require("./assets/images/solar.png"),
      telephone: require("./assets/images/telephone.png"),
      building: require("./assets/images/building.png"),
      light_user: require("./assets/images/light-users.png"),
      water: require("./assets/images/water.png"),
      wifi: require("./assets/images/wifi.png"),
      bank_thin: require("./assets/images/bank-thin.png"),
      city: require("./assets/images/City.png"),
      mobile: require("./assets/images/mobile.png"),

    },
  };
}
